spring:
  application:
    name: test‐com.xuecheng.test.rabbitmq‐producer
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
    virtual-host: virtual-host-abc
    publisher-confirms: true  # 开启发送确认
    publisher-returns: true   # 开启发送失败退回
    listener:   # 开启ACK
      simple:
        acknowledge-mode: manual
#      direct:
#        acknowledge-mode: manual
    template:
      mandatory: true  #保证监听有效，为true时,消息通过交换器无法匹配到队列会触发确认后回调(confirm方法)给生产者，为false不会
    # 重试，超时时间、次数etc

server:
  port: 44001
radom_value: ${random.uuid} #springboot自带生成uuid
